version: '3'

services:
  event-discovery-interface:
    container_name: dev-event-discovery-interface
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      args:
        - NPM_TOKEN=$NPM_TOKEN
    ports:
      - '8156:8156'
