name: CloudFront Invalidation

on:
  schedule:
    - cron: '0 */8 * * *' # Runs every 8 hours

jobs:
  invalidate_cloudfront:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.PRD_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/country/*" "/?category*"
