name: 'Close stale issues'

on:
  schedule:
    - cron: '30 1 * * *'

jobs:

  stale:
    name: Close stale issues
    runs-on: self-hosted
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          days-before-stale: 30
          days-before-close: 5
